### ISSUE TITLE
Tirar colisão cenário sweatbox

### ISSUE THREAD

**Issue by AndreAlmeidavACCPT** [Portugal-vAcc/es-scenario#37]
Ex.:
PSEUDOPILOT:ALL
@N:RYR2093:2200:1:41.2405840:-8.6763950:0:0:4048:0
SIMDATA:RYR2093:*:*:25:1:0.010
$ROUTE:UDRUB PR614 PR634 MANIK
DELAY:12:17

Mudar 0.010 em SIMDATA para 0.000. Aí se dois aviões colidirem (seja no chão ou no ar) deixam de ficar no estado "Aircraft is crashed", e continua a ser possível utilizá-los.

Exemplo acima alterado:
PSEUDOPILOT:ALL
@N:RYR2093:2200:1:41.2405840:-8.6763950:0:0:4048:0
SIMDATA:RYR2093:*:*:25:1:0.000
$ROUTE:UDRUB PR614 PR634 MANIK
DELAY:12:17

**Comment by pikachu1992** [comment]
essa linha não existe na aplicação, envia-me o significado dos paramentros dessa linha sendo que cada : é um parametro

**Comment by AndreAlmeidavACCPT** [comment]
Tirado da Wiki: http://www.euroscope.hu/mediawiki/index.php?title=Scenario_File

" Since v3.2 there are new parameters you can specify for a plane:

IASVARIATION - How much the plane should deviate from the normal IAS. It can be between 0 and 20.
INITIALPSEUDOPILOT - This line defines who will be the pseudo pilot of the plane. If the callsign is logging in, the pseudo pilot state is transferred to that controller immediately.
SIMDATA - It determinates some additional data for tower view and ground simulations.
Examples:

INITIALPSEUDOPILOT:<callsign>
INITIALPSEUDOPILOT:ACCHU06
SIMDATA:<callsign>:<plane type>:<lt;livery>[:>maximum taxi speed>:[>taxiway usage<[>object extent<]]]
Where:

plane type - can be "*" to use the one from the flight plan, or another type to override it. This type of aircraft should be available in the FSX or P3D SimObjects. Here you can also set the "title field" from "aircraft.cfg" from the simulator to display other vehicles such as Follow Me. You also have to set the callsign with " [VHCL]" suffix.
livery - can be "*" to use the first three letters from the callsign, or another type to override it. This livery should be available in the FSX or P3D SimObjects.
maximum taxi speed - When you simulate other type of ground vehicles you may would like to define the maximal taxi speed of them. The value can be between 5 and 50.
taxiway usage - It determines which taxiways can be used by the vehicle. It is very useful when you would like to simulate other ground vehicles than planes. See the taxiway definitions in the ESE Files Description. If the value there and this with bitwise AND is 0 the taxiway is not used by this vehicle.
object extent - The size of the vehicle. This value is used to detect collision on the ground. Set to 0 to disable this feature.
SIMDATA:MAH782:B737:MAH:25:3:0.010 "

**Comment by pikachu1992** [comment]
#38 

Testa este output:
[output.txt](https://github.com/Portugal-vAcc/es-scenario/files/2809241/output.txt)

**Comment by AndreAlmeidavACCPT** [comment]
Funciona.
