### ISSUE TITLE
Lisboa RWY 21 Settings

### ISSUE THREAD

**Issue by pedro2555** [Portugal-vAcc/es-scenario#9]
- [x] departure positions

- [x] arrival routes

**Comment by pikachu1992** [comment]
- Arrival Routes RWY21: https://github.com/Portugal-vAcc/es-scenario/pull/17/commits/ee1913ca10f4d1221cae290cfeae94f513944c52

**Comment by pikachu1992** [comment]
departure positions, estamos a falar dos stands?

**Comment by pedro2555** [comment]
added in 207aed2a87d8e74b22ba001900e919d8339b889a
